/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busbooking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author akash004
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_adminuname = new javax.swing.JTextField();
        btn_admin_login = new javax.swing.JButton();
        btn_admin_reset = new javax.swing.JButton();
        btn_adminca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_adminul = new javax.swing.JButton();
        tf_adminpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("USER NAME");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD");

        tf_adminuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_adminunameActionPerformed(evt);
            }
        });

        btn_admin_login.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_admin_login.setForeground(new java.awt.Color(128, 0, 128));
        btn_admin_login.setText("LOGIN");
        btn_admin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_loginActionPerformed(evt);
            }
        });

        btn_admin_reset.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_admin_reset.setForeground(new java.awt.Color(128, 0, 128));
        btn_admin_reset.setText("RESET");
        btn_admin_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_resetActionPerformed(evt);
            }
        });

        btn_adminca.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        btn_adminca.setText("CREATE ACCOUNT");
        btn_adminca.setActionCommand("CREATE  ACCOUNT");
        btn_adminca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admincaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 0, 128));
        jLabel1.setText("ADMIN LOGIN");

        btn_adminul.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_adminul.setText("User Login");
        btn_adminul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 213, Short.MAX_VALUE)
                .addComponent(btn_adminca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(btn_adminul, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btn_admin_login, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btn_admin_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_adminuname, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(tf_adminpass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_adminuname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_admin_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_admin_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adminca)
                    .addComponent(btn_adminul))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void infoMessage(String message,String tittle)
{

JOptionPane.showMessageDialog(null,message,tittle,JOptionPane.INFORMATION_MESSAGE);

}
    private void tf_adminunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_adminunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_adminunameActionPerformed

    private void btn_adminulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminulActionPerformed
        // TODO add your handling code here:
        dispose();
        UserLogin ul=new UserLogin();
        ul.setLocationRelativeTo(null);
        ul.setVisible(true);
    }//GEN-LAST:event_btn_adminulActionPerformed

    private void btn_admincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admincaActionPerformed
        // TODO add your handling code here:;
        
        dispose();
        CreateAccount ca=new CreateAccount();
        ca.setLocationRelativeTo(null);
        ca.setVisible(true);
    }//GEN-LAST:event_btn_admincaActionPerformed

    private void btn_admin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_loginActionPerformed
        // TODO add your handling code here:
            String username=tf_adminuname.getText();
        String password=tf_adminpass.getText();
       // String email=tf_email.getText();
        try
    {
         Class.forName("com.mysql.cj.jdbc.Driver");
            //  con=DriverManager.getConnection( databaseUrl, "root", "akash");
       Connection  con=DriverManager.getConnection("jdbc:mysql://localhost/busbooking","root","akash");
        Statement stat=con.createStatement();
    //   String selectquery="select * from users_details";
               
               String selectquery="select * from admin_details where username='"+username+"'and password='"+password+"'";
        ResultSet rs=stat.executeQuery(selectquery);
      
        if(rs.next())
        {
        

            
                infoMessage("welcome","Correct.!!");
                dispose();
                AdmincontrolPanel acp=new AdmincontrolPanel(username);
                acp.setLocationRelativeTo(null);
                acp.setVisible(true);
        }
        else
        {
         
                infoMessage("Invalide username or password try again..!!","Error.. !!");
            
           
        }   

                    


    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,"not connect to server and message is"+e.getMessage());
    }
         
       
                                       
                                           
    }//GEN-LAST:event_btn_admin_loginActionPerformed

    private void btn_admin_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_resetActionPerformed
        // TODO add your handling code here:
       tf_adminuname.setText(null);
        tf_adminpass.setText(null);
    }//GEN-LAST:event_btn_admin_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin_login;
    private javax.swing.JButton btn_admin_reset;
    private javax.swing.JButton btn_adminca;
    private javax.swing.JButton btn_adminul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tf_adminpass;
    private javax.swing.JTextField tf_adminuname;
    // End of variables declaration//GEN-END:variables
}
